// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AltDonem struct {
	Ad        string `json:"ad"`
	Baslangic string `json:"baslangic"`
	Bitis     string `json:"bitis"`
}

type AltDonemGirdi struct {
	Ad        string `json:"ad"`
	Baslangic string `json:"baslangic"`
	Bitis     string `json:"bitis"`
}

type CikarimMeta struct {
	AlanYolu    string   `json:"alanYolu"`
	Guven       *float64 `json:"guven,omitempty"`
	KaynakSayfa *int32   `json:"kaynakSayfa,omitempty"`
	KaynakMadde *string  `json:"kaynakMadde,omitempty"`
}

type CikarimMetaGirdi struct {
	AlanYolu    string   `json:"alanYolu"`
	Guven       *float64 `json:"guven,omitempty"`
	KaynakSayfa *int32   `json:"kaynakSayfa,omitempty"`
	KaynakMadde *string  `json:"kaynakMadde,omitempty"`
}

type CocukPolitikasi struct {
	YasMin       *float64 `json:"yasMin,omitempty"`
	YasMax       *float64 `json:"yasMax,omitempty"`
	IndirimYuzde *float64 `json:"indirimYuzde,omitempty"`
	Ucretsiz     *bool    `json:"ucretsiz,omitempty"`
	Kosul        *string  `json:"kosul,omitempty"`
}

type CocukPolitikasiGirdi struct {
	YasMin       *float64 `json:"yasMin,omitempty"`
	YasMax       *float64 `json:"yasMax,omitempty"`
	IndirimYuzde *float64 `json:"indirimYuzde,omitempty"`
	Ucretsiz     *bool    `json:"ucretsiz,omitempty"`
	Kosul        *string  `json:"kosul,omitempty"`
}

type Donem struct {
	Baslangic   *string     `json:"baslangic,omitempty"`
	Bitis       *string     `json:"bitis,omitempty"`
	AltDonemler []*AltDonem `json:"altDonemler,omitempty"`
}

type DonemGirdi struct {
	Baslangic   *string          `json:"baslangic,omitempty"`
	Bitis       *string          `json:"bitis,omitempty"`
	AltDonemler []*AltDonemGirdi `json:"altDonemler,omitempty"`
}

type Fiyat struct {
	OdaTipi    string      `json:"odaTipi"`
	Pansiyon   *Pansiyon   `json:"pansiyon,omitempty"`
	Tutar      float64     `json:"tutar"`
	Birim      FiyatBirimi `json:"birim"`
	AltDonemAd *string     `json:"altDonemAd,omitempty"`
}

type FiyatGirdi struct {
	OdaTipi    string      `json:"odaTipi"`
	Pansiyon   *Pansiyon   `json:"pansiyon,omitempty"`
	Tutar      float64     `json:"tutar"`
	Birim      FiyatBirimi `json:"birim"`
	AltDonemAd *string     `json:"altDonemAd,omitempty"`
}

type IptalKosulu struct {
	Kapsam           *string `json:"kapsam,omitempty"`
	Gun              *int32  `json:"gun,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type IptalKosuluGirdi struct {
	Kapsam           *string `json:"kapsam,omitempty"`
	Gun              *int32  `json:"gun,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type Mutation struct {
}

type NoShow struct {
	SorumluTaraf     *string `json:"sorumluTaraf,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type NoShowGirdi struct {
	SorumluTaraf     *string `json:"sorumluTaraf,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type OdaKontenjani struct {
	OdaTipi  string  `json:"odaTipi"`
	Adet     int32   `json:"adet"`
	Aciklama *string `json:"aciklama,omitempty"`
}

type OdaKontenjaniGirdi struct {
	OdaTipi  string  `json:"odaTipi"`
	Adet     int32   `json:"adet"`
	Aciklama *string `json:"aciklama,omitempty"`
}

type Odeme struct {
	FaturaSonrasiGun *int32  `json:"faturaSonrasiGun,omitempty"`
	AvansVar         *bool   `json:"avansVar,omitempty"`
	AvansAciklama    *string `json:"avansAciklama,omitempty"`
}

type OdemeGirdi struct {
	FaturaSonrasiGun *int32  `json:"faturaSonrasiGun,omitempty"`
	AvansVar         *bool   `json:"avansVar,omitempty"`
	AvansAciklama    *string `json:"avansAciklama,omitempty"`
}

type Overbooking struct {
	SorumluTaraf *string `json:"sorumluTaraf,omitempty"`
	Aciklama     *string `json:"aciklama,omitempty"`
}

type OverbookingGirdi struct {
	SorumluTaraf *string `json:"sorumluTaraf,omitempty"`
	Aciklama     *string `json:"aciklama,omitempty"`
}

type Query struct {
}

type ReleaseKurali struct {
	Gun         int32           `json:"gun"`
	Kapsam      *ReleaseKapsami `json:"kapsam,omitempty"`
	KaynakIfade *string         `json:"kaynakIfade,omitempty"`
}

type ReleaseKuraliGirdi struct {
	Gun         int32           `json:"gun"`
	Kapsam      *ReleaseKapsami `json:"kapsam,omitempty"`
	KaynakIfade *string         `json:"kaynakIfade,omitempty"`
}

type Sozlesme struct {
	ID               string             `json:"id"`
	OlusturmaTarihi  time.Time          `json:"olusturmaTarihi"`
	GuncellemeTarihi time.Time          `json:"guncellemeTarihi"`
	Durum            SozlesmeDurumu     `json:"durum"`
	DosyaAdi         *string            `json:"dosyaAdi,omitempty"`
	Meta             *SozlesmeMeta      `json:"meta,omitempty"`
	Donem            *Donem             `json:"donem,omitempty"`
	OdaKontenjanlari []*OdaKontenjani   `json:"odaKontenjanlari,omitempty"`
	Fiyatlar         []*Fiyat           `json:"fiyatlar,omitempty"`
	Release          *ReleaseKurali     `json:"release,omitempty"`
	StopSale         []*StopSaleAraligi `json:"stopSale,omitempty"`
	CocukPolitikasi  []*CocukPolitikasi `json:"cocukPolitikasi,omitempty"`
	IptalKosullari   []*IptalKosulu     `json:"iptalKosullari,omitempty"`
	NoShow           *NoShow            `json:"noShow,omitempty"`
	Overbooking      *Overbooking       `json:"overbooking,omitempty"`
	Odeme            *Odeme             `json:"odeme,omitempty"`
	CikarimMeta      []*CikarimMeta     `json:"cikarimMeta,omitempty"`
}

type SozlesmeGirdi struct {
	DosyaAdi         *string                 `json:"dosyaAdi,omitempty"`
	Durum            *SozlesmeDurumu         `json:"durum,omitempty"`
	Meta             *SozlesmeMetaGirdi      `json:"meta,omitempty"`
	Donem            *DonemGirdi             `json:"donem,omitempty"`
	OdaKontenjanlari []*OdaKontenjaniGirdi   `json:"odaKontenjanlari,omitempty"`
	Fiyatlar         []*FiyatGirdi           `json:"fiyatlar,omitempty"`
	Release          *ReleaseKuraliGirdi     `json:"release,omitempty"`
	StopSale         []*StopSaleAraligiGirdi `json:"stopSale,omitempty"`
	CocukPolitikasi  []*CocukPolitikasiGirdi `json:"cocukPolitikasi,omitempty"`
	IptalKosullari   []*IptalKosuluGirdi     `json:"iptalKosullari,omitempty"`
	NoShow           *NoShowGirdi            `json:"noShow,omitempty"`
	Overbooking      *OverbookingGirdi       `json:"overbooking,omitempty"`
	Odeme            *OdemeGirdi             `json:"odeme,omitempty"`
	CikarimMeta      []*CikarimMetaGirdi     `json:"cikarimMeta,omitempty"`
}

type SozlesmeMeta struct {
	OtelAdi        *string       `json:"otelAdi,omitempty"`
	AcenteAdi      *string       `json:"acenteAdi,omitempty"`
	SozlesmeTipi   *SozlesmeTipi `json:"sozlesmeTipi,omitempty"`
	Sezon          *Sezon        `json:"sezon,omitempty"`
	ParaBirimi     *string       `json:"paraBirimi,omitempty"`
	KurEsasi       *KurEsasi     `json:"kurEsasi,omitempty"`
	YetkiliMahkeme *string       `json:"yetkiliMahkeme,omitempty"`
	ImzaTarihi     *string       `json:"imzaTarihi,omitempty"`
}

type SozlesmeMetaGirdi struct {
	OtelAdi        *string       `json:"otelAdi,omitempty"`
	AcenteAdi      *string       `json:"acenteAdi,omitempty"`
	SozlesmeTipi   *SozlesmeTipi `json:"sozlesmeTipi,omitempty"`
	Sezon          *Sezon        `json:"sezon,omitempty"`
	ParaBirimi     *string       `json:"paraBirimi,omitempty"`
	KurEsasi       *KurEsasi     `json:"kurEsasi,omitempty"`
	YetkiliMahkeme *string       `json:"yetkiliMahkeme,omitempty"`
	ImzaTarihi     *string       `json:"imzaTarihi,omitempty"`
}

type StopSaleAraligi struct {
	Baslangic       *string          `json:"baslangic,omitempty"`
	Bitis           *string          `json:"bitis,omitempty"`
	Kapsam          *string          `json:"kapsam,omitempty"`
	BildirimYontemi *BildirimYontemi `json:"bildirimYontemi,omitempty"`
	KaynakIfade     *string          `json:"kaynakIfade,omitempty"`
}

type StopSaleAraligiGirdi struct {
	Baslangic       *string          `json:"baslangic,omitempty"`
	Bitis           *string          `json:"bitis,omitempty"`
	Kapsam          *string          `json:"kapsam,omitempty"`
	BildirimYontemi *BildirimYontemi `json:"bildirimYontemi,omitempty"`
	KaynakIfade     *string          `json:"kaynakIfade,omitempty"`
}
