// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AltDonem struct {
	Ad        string `json:"ad"`
	Baslangic string `json:"baslangic"`
	Bitis     string `json:"bitis"`
}

type AltDonemGirdi struct {
	Ad        string `json:"ad"`
	Baslangic string `json:"baslangic"`
	Bitis     string `json:"bitis"`
}

type Cihaz struct {
	ID             string    `json:"id"`
	Ad             string    `json:"ad"`
	Guvenilir      bool      `json:"guvenilir"`
	IlkGorulme     time.Time `json:"ilkGorulme"`
	SonGorulme     time.Time `json:"sonGorulme"`
	IPAdresi       *string   `json:"ipAdresi,omitempty"`
	KullaniciAjani *string   `json:"kullaniciAjani,omitempty"`
}

type CikarimMeta struct {
	AlanYolu    string   `json:"alanYolu"`
	Guven       *float64 `json:"guven,omitempty"`
	KaynakSayfa *int32   `json:"kaynakSayfa,omitempty"`
	KaynakMadde *string  `json:"kaynakMadde,omitempty"`
}

type CikarimMetaGirdi struct {
	AlanYolu    string   `json:"alanYolu"`
	Guven       *float64 `json:"guven,omitempty"`
	KaynakSayfa *int32   `json:"kaynakSayfa,omitempty"`
	KaynakMadde *string  `json:"kaynakMadde,omitempty"`
}

type CocukPolitikasi struct {
	YasMin       *float64 `json:"yasMin,omitempty"`
	YasMax       *float64 `json:"yasMax,omitempty"`
	IndirimYuzde *float64 `json:"indirimYuzde,omitempty"`
	Ucretsiz     *bool    `json:"ucretsiz,omitempty"`
	Kosul        *string  `json:"kosul,omitempty"`
}

type CocukPolitikasiGirdi struct {
	YasMin       *float64 `json:"yasMin,omitempty"`
	YasMax       *float64 `json:"yasMax,omitempty"`
	IndirimYuzde *float64 `json:"indirimYuzde,omitempty"`
	Ucretsiz     *bool    `json:"ucretsiz,omitempty"`
	Kosul        *string  `json:"kosul,omitempty"`
}

type Donem struct {
	Baslangic   *string     `json:"baslangic,omitempty"`
	Bitis       *string     `json:"bitis,omitempty"`
	AltDonemler []*AltDonem `json:"altDonemler,omitempty"`
}

type DonemGirdi struct {
	Baslangic   *string          `json:"baslangic,omitempty"`
	Bitis       *string          `json:"bitis,omitempty"`
	AltDonemler []*AltDonemGirdi `json:"altDonemler,omitempty"`
}

type Fiyat struct {
	OdaTipi    string      `json:"odaTipi"`
	Pansiyon   *Pansiyon   `json:"pansiyon,omitempty"`
	Tutar      float64     `json:"tutar"`
	Birim      FiyatBirimi `json:"birim"`
	AltDonemAd *string     `json:"altDonemAd,omitempty"`
}

type FiyatGirdi struct {
	OdaTipi    string      `json:"odaTipi"`
	Pansiyon   *Pansiyon   `json:"pansiyon,omitempty"`
	Tutar      float64     `json:"tutar"`
	Birim      FiyatBirimi `json:"birim"`
	AltDonemAd *string     `json:"altDonemAd,omitempty"`
}

type GirisSonucu struct {
	MfaGerekli  bool   `json:"mfaGerekli"`
	GeciciToken string `json:"geciciToken"`
}

type IptalKosulu struct {
	Kapsam           *string `json:"kapsam,omitempty"`
	Gun              *int32  `json:"gun,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type IptalKosuluGirdi struct {
	Kapsam           *string `json:"kapsam,omitempty"`
	Gun              *int32  `json:"gun,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type KayitSonucu struct {
	Basarili bool   `json:"basarili"`
	Mesaj    string `json:"mesaj"`
}

type Mutation struct {
}

type NoShow struct {
	SorumluTaraf     *string `json:"sorumluTaraf,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type NoShowGirdi struct {
	SorumluTaraf     *string `json:"sorumluTaraf,omitempty"`
	TazminatAciklama *string `json:"tazminatAciklama,omitempty"`
}

type OdaKontenjani struct {
	OdaTipi  string  `json:"odaTipi"`
	Adet     int32   `json:"adet"`
	Aciklama *string `json:"aciklama,omitempty"`
}

type OdaKontenjaniGirdi struct {
	OdaTipi  string  `json:"odaTipi"`
	Adet     int32   `json:"adet"`
	Aciklama *string `json:"aciklama,omitempty"`
}

type Odeme struct {
	FaturaSonrasiGun *int32  `json:"faturaSonrasiGun,omitempty"`
	AvansVar         *bool   `json:"avansVar,omitempty"`
	AvansAciklama    *string `json:"avansAciklama,omitempty"`
}

type OdemeGirdi struct {
	FaturaSonrasiGun *int32  `json:"faturaSonrasiGun,omitempty"`
	AvansVar         *bool   `json:"avansVar,omitempty"`
	AvansAciklama    *string `json:"avansAciklama,omitempty"`
}

type Organizasyon struct {
	ID              string             `json:"id"`
	Ad              string             `json:"ad"`
	VergiNo         *string            `json:"vergiNo,omitempty"`
	Durum           OrganizasyonDurumu `json:"durum"`
	OlusturmaTarihi time.Time          `json:"olusturmaTarihi"`
}

type OturumBilgisi struct {
	ID              string    `json:"id"`
	OlusturmaTarihi time.Time `json:"olusturmaTarihi"`
	SonKullanma     time.Time `json:"sonKullanma"`
	IPAdresi        *string   `json:"ipAdresi,omitempty"`
	KullaniciAjani  *string   `json:"kullaniciAjani,omitempty"`
	MevcutMu        bool      `json:"mevcutMu"`
}

type OturumSonucu struct {
	ErisimJetonu   string `json:"erisimJetonu"`
	YenilemeJetonu string `json:"yenilemeJetonu"`
}

type Overbooking struct {
	SorumluTaraf *string `json:"sorumluTaraf,omitempty"`
	Aciklama     *string `json:"aciklama,omitempty"`
}

type OverbookingGirdi struct {
	SorumluTaraf *string `json:"sorumluTaraf,omitempty"`
	Aciklama     *string `json:"aciklama,omitempty"`
}

type Query struct {
}

type ReleaseKurali struct {
	Gun         int32           `json:"gun"`
	Kapsam      *ReleaseKapsami `json:"kapsam,omitempty"`
	KaynakIfade *string         `json:"kaynakIfade,omitempty"`
}

type ReleaseKuraliGirdi struct {
	Gun         int32           `json:"gun"`
	Kapsam      *ReleaseKapsami `json:"kapsam,omitempty"`
	KaynakIfade *string         `json:"kaynakIfade,omitempty"`
}

type Sozlesme struct {
	ID               string             `json:"id"`
	OlusturmaTarihi  time.Time          `json:"olusturmaTarihi"`
	GuncellemeTarihi time.Time          `json:"guncellemeTarihi"`
	Durum            SozlesmeDurumu     `json:"durum"`
	DosyaAdi         *string            `json:"dosyaAdi,omitempty"`
	Meta             *SozlesmeMeta      `json:"meta,omitempty"`
	Donem            *Donem             `json:"donem,omitempty"`
	OdaKontenjanlari []*OdaKontenjani   `json:"odaKontenjanlari,omitempty"`
	Fiyatlar         []*Fiyat           `json:"fiyatlar,omitempty"`
	Release          *ReleaseKurali     `json:"release,omitempty"`
	StopSale         []*StopSaleAraligi `json:"stopSale,omitempty"`
	CocukPolitikasi  []*CocukPolitikasi `json:"cocukPolitikasi,omitempty"`
	IptalKosullari   []*IptalKosulu     `json:"iptalKosullari,omitempty"`
	NoShow           *NoShow            `json:"noShow,omitempty"`
	Overbooking      *Overbooking       `json:"overbooking,omitempty"`
	Odeme            *Odeme             `json:"odeme,omitempty"`
	CikarimMeta      []*CikarimMeta     `json:"cikarimMeta,omitempty"`
}

type SozlesmeGirdi struct {
	DosyaAdi         *string                 `json:"dosyaAdi,omitempty"`
	Durum            *SozlesmeDurumu         `json:"durum,omitempty"`
	Meta             *SozlesmeMetaGirdi      `json:"meta,omitempty"`
	Donem            *DonemGirdi             `json:"donem,omitempty"`
	OdaKontenjanlari []*OdaKontenjaniGirdi   `json:"odaKontenjanlari,omitempty"`
	Fiyatlar         []*FiyatGirdi           `json:"fiyatlar,omitempty"`
	Release          *ReleaseKuraliGirdi     `json:"release,omitempty"`
	StopSale         []*StopSaleAraligiGirdi `json:"stopSale,omitempty"`
	CocukPolitikasi  []*CocukPolitikasiGirdi `json:"cocukPolitikasi,omitempty"`
	IptalKosullari   []*IptalKosuluGirdi     `json:"iptalKosullari,omitempty"`
	NoShow           *NoShowGirdi            `json:"noShow,omitempty"`
	Overbooking      *OverbookingGirdi       `json:"overbooking,omitempty"`
	Odeme            *OdemeGirdi             `json:"odeme,omitempty"`
	CikarimMeta      []*CikarimMetaGirdi     `json:"cikarimMeta,omitempty"`
}

type SozlesmeMeta struct {
	OtelAdi        *string       `json:"otelAdi,omitempty"`
	AcenteAdi      *string       `json:"acenteAdi,omitempty"`
	SozlesmeTipi   *SozlesmeTipi `json:"sozlesmeTipi,omitempty"`
	Sezon          *Sezon        `json:"sezon,omitempty"`
	ParaBirimi     *string       `json:"paraBirimi,omitempty"`
	KurEsasi       *KurEsasi     `json:"kurEsasi,omitempty"`
	YetkiliMahkeme *string       `json:"yetkiliMahkeme,omitempty"`
	ImzaTarihi     *string       `json:"imzaTarihi,omitempty"`
}

type SozlesmeMetaGirdi struct {
	OtelAdi        *string       `json:"otelAdi,omitempty"`
	AcenteAdi      *string       `json:"acenteAdi,omitempty"`
	SozlesmeTipi   *SozlesmeTipi `json:"sozlesmeTipi,omitempty"`
	Sezon          *Sezon        `json:"sezon,omitempty"`
	ParaBirimi     *string       `json:"paraBirimi,omitempty"`
	KurEsasi       *KurEsasi     `json:"kurEsasi,omitempty"`
	YetkiliMahkeme *string       `json:"yetkiliMahkeme,omitempty"`
	ImzaTarihi     *string       `json:"imzaTarihi,omitempty"`
}

type StopSaleAraligi struct {
	Baslangic       *string          `json:"baslangic,omitempty"`
	Bitis           *string          `json:"bitis,omitempty"`
	Kapsam          *string          `json:"kapsam,omitempty"`
	BildirimYontemi *BildirimYontemi `json:"bildirimYontemi,omitempty"`
	KaynakIfade     *string          `json:"kaynakIfade,omitempty"`
}

type StopSaleAraligiGirdi struct {
	Baslangic       *string          `json:"baslangic,omitempty"`
	Bitis           *string          `json:"bitis,omitempty"`
	Kapsam          *string          `json:"kapsam,omitempty"`
	BildirimYontemi *BildirimYontemi `json:"bildirimYontemi,omitempty"`
	KaynakIfade     *string          `json:"kaynakIfade,omitempty"`
}

type Uye struct {
	ID        string    `json:"id"`
	Eposta    string    `json:"eposta"`
	Rol       Rol       `json:"rol"`
	HesapTipi HesapTipi `json:"hesapTipi"`
}

type HesapTipi string

const (
	HesapTipiBireysel HesapTipi = "BIREYSEL"
	HesapTipiKurumsal HesapTipi = "KURUMSAL"
)

var AllHesapTipi = []HesapTipi{
	HesapTipiBireysel,
	HesapTipiKurumsal,
}

func (e HesapTipi) IsValid() bool {
	switch e {
	case HesapTipiBireysel, HesapTipiKurumsal:
		return true
	}
	return false
}

func (e HesapTipi) String() string {
	return string(e)
}

func (e *HesapTipi) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HesapTipi(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HesapTipi", str)
	}
	return nil
}

func (e HesapTipi) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HesapTipi) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HesapTipi) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrganizasyonDurumu string

const (
	OrganizasyonDurumuAktif  OrganizasyonDurumu = "AKTIF"
	OrganizasyonDurumuAskida OrganizasyonDurumu = "ASKIDA"
)

var AllOrganizasyonDurumu = []OrganizasyonDurumu{
	OrganizasyonDurumuAktif,
	OrganizasyonDurumuAskida,
}

func (e OrganizasyonDurumu) IsValid() bool {
	switch e {
	case OrganizasyonDurumuAktif, OrganizasyonDurumuAskida:
		return true
	}
	return false
}

func (e OrganizasyonDurumu) String() string {
	return string(e)
}

func (e *OrganizasyonDurumu) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizasyonDurumu(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizasyonDurumu", str)
	}
	return nil
}

func (e OrganizasyonDurumu) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrganizasyonDurumu) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrganizasyonDurumu) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Rol string

const (
	RolSahip         Rol = "SAHIP"
	RolYonetici      Rol = "YONETICI"
	RolGoruntuleyici Rol = "GORUNTULEYICI"
)

var AllRol = []Rol{
	RolSahip,
	RolYonetici,
	RolGoruntuleyici,
}

func (e Rol) IsValid() bool {
	switch e {
	case RolSahip, RolYonetici, RolGoruntuleyici:
		return true
	}
	return false
}

func (e Rol) String() string {
	return string(e)
}

func (e *Rol) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Rol(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Rol", str)
	}
	return nil
}

func (e Rol) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Rol) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Rol) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
