package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/oz-fatma/kontrata/backend/graph/model"
)

// SozlesmeOlustur is the resolver for the sozlesmeOlustur field.
func (r *mutationResolver) SozlesmeOlustur(ctx context.Context, girdi model.SozlesmeGirdi) (*model.Sozlesme, error) {
	return r.Service.Create(ctx, girdi)
}

// SozlesmeGuncelle is the resolver for the sozlesmeGuncelle field.
func (r *mutationResolver) SozlesmeGuncelle(ctx context.Context, id string, girdi model.SozlesmeGirdi) (*model.Sozlesme, error) {
	return r.Service.Update(ctx, id, girdi)
}

// SozlesmeSil is the resolver for the sozlesmeSil field.
func (r *mutationResolver) SozlesmeSil(ctx context.Context, id string) (bool, error) {
	return r.Service.Delete(ctx, id)
}

// KayitOl is the resolver for the kayitOl field.
func (r *mutationResolver) KayitOl(ctx context.Context, eposta string, sifre string) (*model.KayitSonucu, error) {
	return r.Auth.KayitOl(ctx, eposta, sifre)
}

// EpostaDogrula is the resolver for the epostaDogrula field.
func (r *mutationResolver) EpostaDogrula(ctx context.Context, token string) (bool, error) {
	return r.Auth.EpostaDogrula(ctx, token)
}

// DogrulamaTekrarGonder is the resolver for the dogrulamaTekrarGonder field.
func (r *mutationResolver) DogrulamaTekrarGonder(ctx context.Context, eposta string) (bool, error) {
	return r.Auth.DogrulamaTekrarGonder(ctx, eposta)
}

// SifreSifirlamaIste is the resolver for the sifreSifirlamaIste field.
func (r *mutationResolver) SifreSifirlamaIste(ctx context.Context, eposta string) (bool, error) {
	return r.Auth.SifreSifirlamaIste(ctx, eposta)
}

// SifreSifirla is the resolver for the sifreSifirla field.
func (r *mutationResolver) SifreSifirla(ctx context.Context, token string, yeniSifre string) (bool, error) {
	return r.Auth.SifreSifirla(ctx, token, yeniSifre)
}

// Sozlesmeler is the resolver for the sozlesmeler field.
func (r *queryResolver) Sozlesmeler(ctx context.Context, limit *int32, offset *int32) ([]*model.Sozlesme, error) {
	return r.Service.List(ctx, limit, offset)
}

// Sozlesme is the resolver for the sozlesme field.
func (r *queryResolver) Sozlesme(ctx context.Context, id string) (*model.Sozlesme, error) {
	s, err := r.Service.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return s, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
