package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/oz-fatma/kontrata/backend/graph/model"
)

// SozlesmeOlustur is the resolver for the sozlesmeOlustur field.
func (r *mutationResolver) SozlesmeOlustur(ctx context.Context, girdi model.SozlesmeGirdi) (*model.Sozlesme, error) {
	return r.Service.Create(ctx, girdi)
}

// SozlesmeGuncelle is the resolver for the sozlesmeGuncelle field.
func (r *mutationResolver) SozlesmeGuncelle(ctx context.Context, id string, girdi model.SozlesmeGirdi) (*model.Sozlesme, error) {
	return r.Service.Update(ctx, id, girdi)
}

// SozlesmeSil is the resolver for the sozlesmeSil field.
func (r *mutationResolver) SozlesmeSil(ctx context.Context, id string) (bool, error) {
	return r.Service.Delete(ctx, id)
}

// KayitOl is the resolver for the kayitOl field.
func (r *mutationResolver) KayitOl(ctx context.Context, eposta string, sifre string) (*model.KayitSonucu, error) {
	return r.Auth.KayitOl(ctx, eposta, sifre)
}

// EpostaDogrula is the resolver for the epostaDogrula field.
func (r *mutationResolver) EpostaDogrula(ctx context.Context, token string) (bool, error) {
	return r.Auth.EpostaDogrula(ctx, token)
}

// DogrulamaTekrarGonder is the resolver for the dogrulamaTekrarGonder field.
func (r *mutationResolver) DogrulamaTekrarGonder(ctx context.Context, eposta string) (bool, error) {
	return r.Auth.DogrulamaTekrarGonder(ctx, eposta)
}

// SifreSifirlamaIste is the resolver for the sifreSifirlamaIste field.
func (r *mutationResolver) SifreSifirlamaIste(ctx context.Context, eposta string) (bool, error) {
	return r.Auth.SifreSifirlamaIste(ctx, eposta)
}

// SifreSifirla is the resolver for the sifreSifirla field.
func (r *mutationResolver) SifreSifirla(ctx context.Context, token string, yeniSifre string) (bool, error) {
	return r.Auth.SifreSifirla(ctx, token, yeniSifre)
}

// GirisYap is the resolver for the girisYap field.
func (r *mutationResolver) GirisYap(ctx context.Context, eposta string, sifre string) (*model.GirisSonucu, error) {
	return r.Auth.GirisYap(ctx, eposta, sifre)
}

// MfaDogrula is the resolver for the mfaDogrula field.
func (r *mutationResolver) MfaDogrula(ctx context.Context, geciciToken string, kod string) (*model.OturumSonucu, error) {
	return r.Auth.MFADogrula(ctx, geciciToken, kod)
}

// JetonYenile is the resolver for the jetonYenile field.
func (r *mutationResolver) JetonYenile(ctx context.Context, yenilemeJetonu string) (*model.OturumSonucu, error) {
	return r.Auth.JetonYenile(ctx, yenilemeJetonu)
}

// CikisYap is the resolver for the cikisYap field.
func (r *mutationResolver) CikisYap(ctx context.Context) (bool, error) {
	return r.Auth.CikisYap(ctx)
}

// TumOturumlariKapat is the resolver for the tumOturumlariKapat field.
func (r *mutationResolver) TumOturumlariKapat(ctx context.Context) (int32, error) {
	return r.Auth.TumOturumlariKapat(ctx)
}

// CihazAdlandir is the resolver for the cihazAdlandir field.
func (r *mutationResolver) CihazAdlandir(ctx context.Context, id string, ad string) (*model.Cihaz, error) {
	return r.Auth.CihazAdlandir(ctx, id, ad)
}

// CihazKaldir is the resolver for the cihazKaldir field.
func (r *mutationResolver) CihazKaldir(ctx context.Context, id string) (bool, error) {
	return r.Auth.CihazKaldir(ctx, id)
}

// CihazGuvenilirYap is the resolver for the cihazGuvenilirYap field.
func (r *mutationResolver) CihazGuvenilirYap(ctx context.Context, id string) (*model.Cihaz, error) {
	return r.Auth.CihazGuvenilirYap(ctx, id)
}

// HesapSilmeIste is the resolver for the hesapSilmeIste field.
func (r *mutationResolver) HesapSilmeIste(ctx context.Context) (bool, error) {
	return r.Auth.HesapSilmeIste(ctx)
}

// HesapSil is the resolver for the hesapSil field.
func (r *mutationResolver) HesapSil(ctx context.Context, token string) (bool, error) {
	return r.Auth.HesapSil(ctx, token)
}

// Sozlesmeler is the resolver for the sozlesmeler field.
func (r *queryResolver) Sozlesmeler(ctx context.Context, limit *int32, offset *int32) ([]*model.Sozlesme, error) {
	return r.Service.List(ctx, limit, offset)
}

// Sozlesme is the resolver for the sozlesme field.
func (r *queryResolver) Sozlesme(ctx context.Context, id string) (*model.Sozlesme, error) {
	s, err := r.Service.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return s, nil
}

// Oturumlarim is the resolver for the oturumlarim field.
func (r *queryResolver) Oturumlarim(ctx context.Context) ([]*model.OturumBilgisi, error) {
	return r.Auth.Oturumlarim(ctx)
}

// Cihazlarim is the resolver for the cihazlarim field.
func (r *queryResolver) Cihazlarim(ctx context.Context) ([]*model.Cihaz, error) {
	return r.Auth.Cihazlarim(ctx)
}

// VerilerimiIndir is the resolver for the verilerimiIndir field.
func (r *queryResolver) VerilerimiIndir(ctx context.Context) (string, error) {
	return r.Auth.VerilerimiIndir(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
