package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/oz-fatma/kontrata/backend/graph/model"
)

// SozlesmeYukle is the resolver for the sozlesmeYukle field.
func (r *mutationResolver) SozlesmeYukle(ctx context.Context, dosya graphql.Upload) (*model.Sozlesme, error) {
	return r.Service.Upload(ctx, dosya.Filename, dosya.File)
}

// SozlesmeOlustur is the resolver for the sozlesmeOlustur field.
func (r *mutationResolver) SozlesmeOlustur(ctx context.Context, girdi model.SozlesmeGirdi) (*model.Sozlesme, error) {
	return r.Service.Create(ctx, girdi)
}

// SozlesmeGuncelle is the resolver for the sozlesmeGuncelle field.
func (r *mutationResolver) SozlesmeGuncelle(ctx context.Context, id string, girdi model.SozlesmeGirdi) (*model.Sozlesme, error) {
	return r.Service.Update(ctx, id, girdi)
}

// SozlesmeOnayla is the resolver for the sozlesmeOnayla field.
func (r *mutationResolver) SozlesmeOnayla(ctx context.Context, id string) (*model.Sozlesme, error) {
	return r.Service.Approve(ctx, id)
}

// SozlesmeAlanGuncelle is the resolver for the sozlesmeAlanGuncelle field.
func (r *mutationResolver) SozlesmeAlanGuncelle(ctx context.Context, id string, alanYolu string, deger interface{}) (*model.Sozlesme, error) {
	return r.Service.UpdateField(ctx, id, alanYolu, deger)
}

// SozlesmeSil is the resolver for the sozlesmeSil field.
func (r *mutationResolver) SozlesmeSil(ctx context.Context, id string) (bool, error) {
	return r.Service.Delete(ctx, id)
}

// KayitOl is the resolver for the kayitOl field.
func (r *mutationResolver) KayitOl(ctx context.Context, eposta string, sifre string, hesapTipi *model.HesapTipi, organizasyonAdi *string) (*model.KayitSonucu, error) {
	return r.Auth.Register(ctx, eposta, sifre, hesapTipi, organizasyonAdi)
}

// EpostaDogrula is the resolver for the epostaDogrula field.
func (r *mutationResolver) EpostaDogrula(ctx context.Context, token string) (bool, error) {
	return r.Auth.VerifyEmail(ctx, token)
}

// DogrulamaTekrarGonder is the resolver for the dogrulamaTekrarGonder field.
func (r *mutationResolver) DogrulamaTekrarGonder(ctx context.Context, eposta string) (bool, error) {
	return r.Auth.ResendVerification(ctx, eposta)
}

// SifreSifirlamaIste is the resolver for the sifreSifirlamaIste field.
func (r *mutationResolver) SifreSifirlamaIste(ctx context.Context, eposta string) (bool, error) {
	return r.Auth.RequestPasswordReset(ctx, eposta)
}

// SifreSifirla is the resolver for the sifreSifirla field.
func (r *mutationResolver) SifreSifirla(ctx context.Context, token string, yeniSifre string) (bool, error) {
	return r.Auth.ResetPassword(ctx, token, yeniSifre)
}

// GirisYap is the resolver for the girisYap field.
func (r *mutationResolver) GirisYap(ctx context.Context, eposta string, sifre string) (*model.GirisSonucu, error) {
	return r.Auth.Login(ctx, eposta, sifre)
}

// MfaDogrula is the resolver for the mfaDogrula field.
func (r *mutationResolver) MfaDogrula(ctx context.Context, geciciToken string, kod string) (*model.OturumSonucu, error) {
	return r.Auth.VerifyMFA(ctx, geciciToken, kod)
}

// JetonYenile is the resolver for the jetonYenile field.
func (r *mutationResolver) JetonYenile(ctx context.Context, yenilemeJetonu string) (*model.OturumSonucu, error) {
	return r.Auth.RefreshToken(ctx, yenilemeJetonu)
}

// CikisYap is the resolver for the cikisYap field.
func (r *mutationResolver) CikisYap(ctx context.Context) (bool, error) {
	return r.Auth.Logout(ctx)
}

// TumOturumlariKapat is the resolver for the tumOturumlariKapat field.
func (r *mutationResolver) TumOturumlariKapat(ctx context.Context) (int32, error) {
	return r.Auth.RevokeOtherSessions(ctx)
}

// CihazAdlandir is the resolver for the cihazAdlandir field.
func (r *mutationResolver) CihazAdlandir(ctx context.Context, id string, ad string) (*model.Cihaz, error) {
	return r.Auth.RenameDevice(ctx, id, ad)
}

// CihazKaldir is the resolver for the cihazKaldir field.
func (r *mutationResolver) CihazKaldir(ctx context.Context, id string) (bool, error) {
	return r.Auth.RemoveDevice(ctx, id)
}

// CihazGuvenilirYap is the resolver for the cihazGuvenilirYap field.
func (r *mutationResolver) CihazGuvenilirYap(ctx context.Context, id string) (*model.Cihaz, error) {
	return r.Auth.TrustDevice(ctx, id)
}

// HesapSilmeIste is the resolver for the hesapSilmeIste field.
func (r *mutationResolver) HesapSilmeIste(ctx context.Context) (bool, error) {
	return r.Auth.RequestAccountDelete(ctx)
}

// HesapSil is the resolver for the hesapSil field.
func (r *mutationResolver) HesapSil(ctx context.Context, token string) (bool, error) {
	return r.Auth.DeleteAccount(ctx, token)
}

// UyeDavetEt is the resolver for the uyeDavetEt field.
func (r *mutationResolver) UyeDavetEt(ctx context.Context, eposta string, rol model.Rol) (bool, error) {
	return r.Auth.InviteMember(ctx, eposta, rol)
}

// DavetiKabulEt is the resolver for the davetiKabulEt field.
func (r *mutationResolver) DavetiKabulEt(ctx context.Context, token string, sifre string) (bool, error) {
	return r.Auth.AcceptInvite(ctx, token, sifre)
}

// UyeRolDegistir is the resolver for the uyeRolDegistir field.
func (r *mutationResolver) UyeRolDegistir(ctx context.Context, kullaniciID string, rol model.Rol) (*model.Uye, error) {
	return r.Auth.ChangeMemberRole(ctx, kullaniciID, rol)
}

// UyeCikar is the resolver for the uyeCikar field.
func (r *mutationResolver) UyeCikar(ctx context.Context, kullaniciID string) (bool, error) {
	return r.Auth.RemoveMember(ctx, kullaniciID)
}

// OrganizasyonSil is the resolver for the organizasyonSil field.
func (r *mutationResolver) OrganizasyonSil(ctx context.Context) (bool, error) {
	return r.Auth.DeleteOrganization(ctx)
}

// PromptGuncelle is the resolver for the promptGuncelle field.
func (r *mutationResolver) PromptGuncelle(ctx context.Context, tip model.PromptTipi, icerik string) (*model.PromptSurumu, error) {
	return r.Auth.UpdatePrompt(ctx, tip, icerik)
}

// PromptSurumeDon is the resolver for the promptSurumeDon field.
func (r *mutationResolver) PromptSurumeDon(ctx context.Context, id string) (*model.PromptSurumu, error) {
	return r.Auth.RevertPrompt(ctx, id)
}

// AyarlariGuncelle is the resolver for the ayarlariGuncelle field.
func (r *mutationResolver) AyarlariGuncelle(ctx context.Context, denetciRiskEsigi *float64, maxToken *int32) (*model.Ayarlar, error) {
	return r.Auth.UpdateSettings(ctx, denetciRiskEsigi, maxToken)
}

// Sozlesmeler is the resolver for the sozlesmeler field.
func (r *queryResolver) Sozlesmeler(ctx context.Context, limit *int32, offset *int32) ([]*model.Sozlesme, error) {
	return r.Service.List(ctx, limit, offset)
}

// Sozlesme is the resolver for the sozlesme field.
func (r *queryResolver) Sozlesme(ctx context.Context, id string) (*model.Sozlesme, error) {
	s, err := r.Service.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return s, nil
}

// Oturumlarim is the resolver for the oturumlarim field.
func (r *queryResolver) Oturumlarim(ctx context.Context) ([]*model.OturumBilgisi, error) {
	return r.Auth.ListSessions(ctx)
}

// Cihazlarim is the resolver for the cihazlarim field.
func (r *queryResolver) Cihazlarim(ctx context.Context) ([]*model.Cihaz, error) {
	return r.Auth.ListDevices(ctx)
}

// VerilerimiIndir is the resolver for the verilerimiIndir field.
func (r *queryResolver) VerilerimiIndir(ctx context.Context) (string, error) {
	return r.Auth.ExportData(ctx)
}

// Organizasyonum is the resolver for the organizasyonum field.
func (r *queryResolver) Organizasyonum(ctx context.Context) (*model.Organizasyon, error) {
	return r.Auth.MyOrganization(ctx)
}

// Uyeler is the resolver for the uyeler field.
func (r *queryResolver) Uyeler(ctx context.Context) ([]*model.Uye, error) {
	return r.Auth.Members(ctx)
}

// PromptSurumleri is the resolver for the promptSurumleri field.
func (r *queryResolver) PromptSurumleri(ctx context.Context, tip model.PromptTipi) ([]*model.PromptSurumu, error) {
	return r.Auth.PromptVersions(ctx, tip)
}

// AktifPrompt is the resolver for the aktifPrompt field.
func (r *queryResolver) AktifPrompt(ctx context.Context, tip model.PromptTipi) (*model.PromptSurumu, error) {
	return r.Auth.ActivePrompt(ctx, tip)
}

// Ayarlar is the resolver for the ayarlar field.
func (r *queryResolver) Ayarlar(ctx context.Context) (*model.Ayarlar, error) {
	return r.Auth.Settings(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
